## QTM 350: Data Science Computing

### Assignment 08: SQL Practice with Python

### Due 02 April 2025

### Instructions:
Use Python's `sqlite3` library to complete the following tasks. Connect to an in-memory SQLite database or create a file named `assignment08.db`.

Ensure all your Python code and the query results (where applicable) are included in this notebook. Submit this `.ipynb` file on Canvas.

Begin by running the setup code cell to create and populate the `drivers` table.

### Setup: Create and Populate Database

In [1]:
import sqlite3
import pandas as pd # Often useful for displaying results

# Connect to the database (or create it)
conn = sqlite3.connect('assignment08.db') 
# conn = sqlite3.connect(':memory:') # Option for in-memory database
cursor = conn.cursor()
print("Database connected.")

# --- Create drivers Table ---
cursor.execute("DROP TABLE IF EXISTS drivers;")
create_table_sql = """
CREATE TABLE drivers(
    driver_id INT PRIMARY KEY,
    driver_name VARCHAR(30),
    nationality VARCHAR(15),
    team VARCHAR(30),
    victories INT,
    podiums INT,
    poles INT,
    points FLOAT
);
"""
cursor.execute(create_table_sql)
print("Table 'drivers' created.")

# --- Insert Data ---
drivers_data = [
    (1, 'Lewis Hamilton', 'British', 'Mercedes', 103, 182, 103, 4160.5),
    (2, 'Michael Schumacher', 'German', 'Ferrari', 91, 155, 68, 1566.0),
    (3, 'Ayrton Senna', 'Brazilian', 'McLaren', 41, 80, 65, 614.0),
    (4, 'Sebastian Vettel', 'German', 'Red Bull', 53, 122, 57, 3097.0),
    (5, 'Niki Lauda', 'Austrian', 'Ferrari', 25, 54, 24, 420.5),
    (6, 'Fernando Alonso', 'Spanish', 'Renault', 32, 101, 22, 2061.0),
    (7, 'Alain Prost', 'French', 'McLaren', 51, 106, 33, 798.5),
    (8, 'Charles Leclerc', 'Monegasque', 'Ferrari', 5, 21, 18, 699.0),
    (9, 'Max Verstappen', 'Dutch', 'Red Bull', 52, 92, 28, 2411.0),
    (10, 'Jenson Button', 'British', 'Brawn GP', 15, 50, 8, 1235.0),
    (11, 'Kimi Raikkonen', 'Finnish', 'Ferrari', 21, 103, 18, 1873.0),
    (12, 'Daniel Ricciardo', 'Australian', 'Red Bull', 8, 32, 3, 1274.0),
    (13, 'Valtteri Bottas', 'Finnish', 'Mercedes', 10, 67, 20, 1731.0),
    (14, 'Rubens Barrichello', 'Brazilian', 'Ferrari', 11, 68, 13, 658.0)
]

insert_sql = "INSERT INTO drivers VALUES (?, ?, ?, ?, ?, ?, ?, ?);"
cursor.executemany(insert_sql, drivers_data)
conn.commit()
print(f"{cursor.rowcount} records inserted into 'drivers'.")

# --- Verify Data Insertion ---
print("\n--- Initial Drivers Data ---")
df_initial = pd.read_sql_query("SELECT * FROM drivers;", conn)
print(df_initial)

Database connected.
Table 'drivers' created.
14 records inserted into 'drivers'.

--- Initial Drivers Data ---
    driver_id         driver_name nationality      team  victories  podiums  \
0           1      Lewis Hamilton     British  Mercedes        103      182
1           2  Michael Schumacher      German   Ferrari         91      155
2           3        Ayrton Senna   Brazilian   McLaren         41       80
3           4    Sebastian Vettel      German  Red Bull         53      122
4           5          Niki Lauda    Austrian   Ferrari         25       54
5           6     Fernando Alonso     Spanish   Renault         32      101
6           7         Alain Prost      French   McLaren         51      106
7           8     Charles Leclerc  Monegasque   Ferrari          5       21
8           9      Max Verstappen       Dutch  Red Bull         52       92
9          10       Jenson Button     British  Brawn GP         15       50
10         11      Kimi Raikkonen     Finnish   Ferrari         21      103
11         12    Daniel Ricciardo  Australian  Red Bull          8       32
12         13     Valtteri Bottas     Finnish  Mercedes         10       67
13         14  Rubens Barrichello   Brazilian   Ferrari         11       68

    poles  points
0     103  4160.5
1      68  1566.0
2      65   614.0
3      57  3097.0
4      24   420.5
5      22  2061.0
6      33   798.5
7      18   699.0
8      28  2411.0
9       8  1235.0
10     18  1873.0
11      3  1274.0
12     20  1731.0
13     13   658.0

1) List drivers ordered by `team` alphabetically and then by `victories` in descending order.

In [3]:
query1 = """
SELECT * FROM drivers
ORDER BY team ASC, victories DESC;
"""
pd.read_sql_query(query1, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,10,Jenson Button,British,Brawn GP,15,50,8,1235.0
1,2,Michael Schumacher,German,Ferrari,91,155,68,1566.0
2,5,Niki Lauda,Austrian,Ferrari,25,54,24,420.5
3,11,Kimi Raikkonen,Finnish,Ferrari,21,103,18,1873.0
4,14,Rubens Barrichello,Brazilian,Ferrari,11,68,13,658.0
5,8,Charles Leclerc,Monegasque,Ferrari,5,21,18,699.0
6,7,Alain Prost,French,McLaren,51,106,33,798.5
7,3,Ayrton Senna,Brazilian,McLaren,41,80,65,614.0
8,1,Lewis Hamilton,British,Mercedes,103,182,103,4160.5
9,13,Valtteri Bottas,Finnish,Mercedes,10,67,20,1731.0
10,4,Sebastian Vettel,German,Red Bull,53,122,57,3097.0
11,9,Max Verstappen,Dutch,Red Bull,52,92,28,2411.0
12,12,Daniel Ricciardo,Australian,Red Bull,8,32,3,1274.0
13,6,Fernando Alonso,Spanish,Renault,32,101,22,2061.0

2) List drivers who have won more races than the average number of victories across all drivers.

In [4]:
query2 = """
SELECT * FROM drivers
WHERE victories > (
    SELECT AVG(victories) FROM drivers
);
"""
pd.read_sql_query(query2, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,1,Lewis Hamilton,British,Mercedes,103,182,103,4160.5
1,2,Michael Schumacher,German,Ferrari,91,155,68,1566.0
2,3,Ayrton Senna,Brazilian,McLaren,41,80,65,614.0
3,4,Sebastian Vettel,German,Red Bull,53,122,57,3097.0
4,7,Alain Prost,French,McLaren,51,106,33,798.5
5,9,Max Verstappen,Dutch,Red Bull,52,92,28,2411.0

3) Find all drivers with more than 50 podiums OR who drive for the 'Ferrari' team.

In [5]:
query3 = """
SELECT * FROM drivers
WHERE podiums > 50 OR team = 'Ferrari';
"""
pd.read_sql_query(query3, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,1,Lewis Hamilton,British,Mercedes,103,182,103,4160.5
1,2,Michael Schumacher,German,Ferrari,91,155,68,1566.0
2,3,Ayrton Senna,Brazilian,McLaren,41,80,65,614.0
3,4,Sebastian Vettel,German,Red Bull,53,122,57,3097.0
4,5,Niki Lauda,Austrian,Ferrari,25,54,24,420.5
5,6,Fernando Alonso,Spanish,Renault,32,101,22,2061.0
6,7,Alain Prost,French,McLaren,51,106,33,798.5
7,8,Charles Leclerc,Monegasque,Ferrari,5,21,18,699.0
8,9,Max Verstappen,Dutch,Red Bull,52,92,28,2411.0
9,11,Kimi Raikkonen,Finnish,Ferrari,21,103,18,1873.0
10,13,Valtteri Bottas,Finnish,Mercedes,10,67,20,1731.0
11,14,Rubens Barrichello,Brazilian,Ferrari,11,68,13,658.0

4) Count the number of drivers for each `nationality`, but only include drivers who have more than 40 `podiums`. Order the result by count in descending order.

In [6]:
query4 = """
SELECT nationality, COUNT(*) as driver_count
FROM drivers
WHERE podiums > 40
GROUP BY nationality
ORDER BY driver_count DESC;
"""
pd.read_sql_query(query4, conn)

  nationality  driver_count
0      German             2
1     Finnish             2
2     British             2
3   Brazilian             2
4     Spanish             1
5      French             1
6       Dutch             1
7    Austrian             1

5) Calculate the average `points` for each `team`, rounded to two decimal places.

In [7]:
query5 = """
SELECT team, ROUND(AVG(points), 2) AS avg_points
FROM drivers
GROUP BY team;
"""
pd.read_sql_query(query5, conn)

       team  avg_points
0  Brawn GP     1235.00
1   Ferrari     1043.30
2   McLaren      706.25
3  Mercedes     2945.75
4  Red Bull     2260.67
5   Renault     2061.00

6) List drivers who are in the top 20% based on their `points`.

In [10]:
# First, get the 80th percentile value
points_df = pd.read_sql_query("SELECT points FROM drivers ORDER BY points DESC;", conn)
threshold = points_df['points'].quantile(0.80)

In [11]:

query6 = f"""
SELECT * FROM drivers
WHERE points >= {threshold};
"""
pd.read_sql_query(query6, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,1,Lewis Hamilton,British,Mercedes,103,182,103,4160.5
1,4,Sebastian Vettel,German,Red Bull,53,122,57,3097.0
2,9,Max Verstappen,Dutch,Red Bull,52,92,28,2411.0

7) Calculate the total `victories`, total `podiums`, and average `points` for drivers with 'German' `nationality`.

In [12]:
query7 = """
SELECT 
    SUM(victories) AS total_victories,
    SUM(podiums) AS total_podiums,
    ROUND(AVG(points), 2) AS avg_points
FROM drivers
WHERE nationality = 'German';
"""
pd.read_sql_query(query7, conn)

   total_victories  total_podiums  avg_points
0              144            277      2331.5

8) List all drivers whose `driver_name` contains both the letter 'a' and the letter 'e' (case-insensitive).

In [13]:
query8 = """
SELECT * FROM drivers
WHERE LOWER(driver_name) LIKE '%a%'
  AND LOWER(driver_name) LIKE '%e%';
"""
pd.read_sql_query(query8, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,1,Lewis Hamilton,British,Mercedes,103,182,103,4160.5
1,2,Michael Schumacher,German,Ferrari,91,155,68,1566.0
2,3,Ayrton Senna,Brazilian,McLaren,41,80,65,614.0
3,4,Sebastian Vettel,German,Red Bull,53,122,57,3097.0
4,6,Fernando Alonso,Spanish,Renault,32,101,22,2061.0
5,8,Charles Leclerc,Monegasque,Ferrari,5,21,18,699.0
6,9,Max Verstappen,Dutch,Red Bull,52,92,28,2411.0
7,11,Kimi Raikkonen,Finnish,Ferrari,21,103,18,1873.0
8,12,Daniel Ricciardo,Australian,Red Bull,8,32,3,1274.0
9,13,Valtteri Bottas,Finnish,Mercedes,10,67,20,1731.0
10,14,Rubens Barrichello,Brazilian,Ferrari,11,68,13,658.0

9) Retrieve the driver with the most `victories` within each `team`.

In [14]:
query9 = """
SELECT d.*
FROM drivers d
INNER JOIN (
    SELECT team, MAX(victories) AS max_victories
    FROM drivers
    GROUP BY team
) tmax ON d.team = tmax.team AND d.victories = tmax.max_victories;
"""
pd.read_sql_query(query9, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,1,Lewis Hamilton,British,Mercedes,103,182,103,4160.5
1,2,Michael Schumacher,German,Ferrari,91,155,68,1566.0
2,4,Sebastian Vettel,German,Red Bull,53,122,57,3097.0
3,6,Fernando Alonso,Spanish,Renault,32,101,22,2061.0
4,7,Alain Prost,French,McLaren,51,106,33,798.5
5,10,Jenson Button,British,Brawn GP,15,50,8,1235.0

10) List drivers whose `points` are below the average `points` for their respective `team`.

In [15]:
query10 = """
SELECT d.*
FROM drivers d
JOIN (
    SELECT team, AVG(points) AS avg_team_points
    FROM drivers
    GROUP BY team
) tavg ON d.team = tavg.team
WHERE d.points < tavg.avg_team_points;
"""
pd.read_sql_query(query10, conn)

,driver_id,driver_name,nationality,team,victories,podiums,poles,points
0,3,Ayrton Senna,Brazilian,McLaren,41,80,65,614.0
1,5,Niki Lauda,Austrian,Ferrari,25,54,24,420.5
2,8,Charles Leclerc,Monegasque,Ferrari,5,21,18,699.0
3,12,Daniel Ricciardo,Australian,Red Bull,8,32,3,1274.0
4,13,Valtteri Bottas,Finnish,Mercedes,10,67,20,1731.0
5,14,Rubens Barrichello,Brazilian,Ferrari,11,68,13,658.0

11) Cleanup: Close the database connection

In [16]:
conn.close()
print("Connection closed.")

Connection closed.